name: check hub
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  hub-validation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: checkout hub
        uses: actions/checkout@v3
        with:
          repository: "crowdsecurity/hub"
          path: hub
      - name: split hub YAML to per-doc JSON (no jq)
        uses: mikefarah/yq@master
        with:
          cmd: |
            set -eu
            # iterate all YAMLs except .tests
            find hub -path hub/.tests -prune -name '*json' -exec rm {} \;
            for f in $(find hub -path hub/.tests -prune -o -name '*yaml' -print); do
            base="${f%.yaml}"  # trim .yaml
            i=0
            while : ; do
               out="${base}.${i}.json"
               # select one YAML document by index (0-based) and write it
               yq -o=json 'select(documentIndex == '"$i"')' "$f" > "$out"
               # empty file => no more docs, clean up and stop
               if [ ! -s "$out" ]; then rm -f "$out"; break; fi
               i=$((i+1))
               done
               echo "split $f -> ${i} JSON doc(s)"
            done
      - name: validate parsers against schema
        run: |
          go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
          for ITEM in ./hub/parsers/*/*/*.json; do echo $ITEM && cat $ITEM &&  ~/go/bin/jv parser_schema.json $ITEM ; done
      - name: validate scenarios against schema
        run: |
          for ITEM in ./hub/scenarios/*/*.json; do echo $ITEM && ~/go/bin/jv scenario_schema.json $ITEM ; done
      - name: validate postoverflows against schema
        run: |
          for ITEM in ./hub/postoverflows/*/*/*.json; do echo $ITEM && ~/go/bin/jv parser_schema.json $ITEM ; done
      - name: validate parsers against schema
        run: |
          for ITEM in ./hub/collections/*/*.json; do echo $ITEM && ~/go/bin/jv collection_schema.json $ITEM ; done
      - name: validate parsers against schema
        run: |
          for ITEM in ./hub/appsec-rules/*/*.json; do echo $ITEM && ~/go/bin/jv appsec_rules_schema.json $ITEM ; done
