name: check hub
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs: 
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: checkout hub
      uses: actions/checkout@v3
      with:
        repository: 'crowdsecurity/hub'
        path: hub
    - name: transform to json all parsers/scenarios/collections/postovfw
      uses: mikefarah/yq@master
      with:
        cmd: find . -path ./.tests -prune -o -name "*"yaml -exec sh -c 'yq  -o=json {} > $(dirname {})/$(basename {} .yaml).json' \;
    - name: transform to json schema
      uses: mikefarah/yq@master
      with:
        cmd: for i in *.yaml ; do yq  -o=json $i > $(basename $i .yaml).json ; done
    - name: "validate against schema"
      run: |
        go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
        find ./hub/parsers -name "*"json \( -exec sh -c 'echo {} && ~/go/bin/jv parser_schema.json {}' \; -o -quit \)
        find ./hub/scenarios -name "*"json \( -exec sh -c 'echo {} && ~/go/bin/jv scenario_schema.json {}' \; -o -quit \)
        find ./hub/collections -name "*"json \( -exec sh -c 'echo {} && ~/go/bin/jv collection_schema.json {}' \; -o -quit \)
        find ./hub/postoverflows -name "*"json \( -exec sh -c 'echo {} && ~/go/bin/jv parser_schema.json {}' \; -o -quit \)
    
