name: Validate
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs: 
  yaml-schema-validation:
    strategy:
      matrix:
        files:
          - parser_schema
          - scenario_schema
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        id: go
    - name: transform to json
      uses: mikefarah/yq@master
      with:
        cmd: yq  -o=json ${{ matrix.files }}.yaml > ${{ matrix.files }}.json
    - name: "validate against schema"
      run: |
        go install github.com/santhosh-tekuri/jsonschema/v5/cmd/jv@latest
        ~/go/bin/jv ${{ matrix.files }}.json
    
