name: Validate
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate YAML Schema
      uses: PaulRitter/yaml-schema-validator@v2
      with:
        path_pattern:  parser_schema.yaml
        schema: http://json-schema.org/draft-04/schema
